### PR TITLE
Add RFC for binary-heaps

### PR DESCRIPTION
**Pull request by Theodus**
[Rendered](https://github.com/ponylang/rfcs/blob/binary-heaps/text/0000-binary-heaps.md)

### CODE REVIEW

**Review by jemc — APPROVED** [review]
Looks good to me.
One small suggestion - for namespace cleanliness' sake, I'd suggest renaming `HeapPriority` as `BinaryHeapPriority`, so that the relationship to `BinaryHeap` is clear.

**Comment by jemc** [comment]
@Theodus - do you want to move this into final comment period, or wait for more discussion to happen first?

**Comment by Theodus** [comment]
I think this is ready for final comment period if no one brought up any concerns during the sync meeting.

**Comment by mfelsche** [comment]
:+1:

**Comment by SeanTAllen** [comment]
This has been accepted. House keeping is needed for creation of issues, etc, can you do that @Theodus ?

**Comment by Theodus** [comment]
@SeanTAllen sure, will do

**Pull request merged**
