### PR TITLE
Add RFC for bare (FFI) lambdas.

### PR DESCRIPTION
**Pull request by jemc**
[Rendered](https://github.com/ponylang/rfcs/blob/bare-ffi-lambdas/text/0000-bare-ffi-lambdas.md).

### CODE REVIEW

**Comment by jemc** [comment]
This RFC is intended to fill request #66.

**Review by Praetonus — APPROVED** [review]
👍

**Comment by SeanTAllen** [comment]
I like this. If I'm not around when this comes up for a vote. I vote yes.

**Comment by jemc** [comment]
Just a note that there are a few changes (mostly additions) coming to the RFC when I get time to write them up, based on some discussion from the last sync call.

**Comment by jemc** [comment]
Moving to final comment period.  Made some additions based on sync call discussion so please take another look.

**Comment by SeanTAllen** [comment]
I vote yes on this.

**Pull request merged**
