### PR TITLE
Generic type inference

### PR DESCRIPTION
**Pull request by Praetonus**
[Rendered](https://github.com/Praetonus/rfcs/blob/generic-inference/text/0000-generic-type-inference.md).

### CODE REVIEW

**Comment by jemc** [comment]
Should we also consider inferring a type's type parameter if it is included in the constructor?

For example:

``` pony
class Foo[A]
  new create(a: A) => // ...
```

``` pony
let x = Foo("hello")
// inferred as:
let x = Foo[String]("hello")
```

**Comment by Praetonus** [comment]
Yes, I don't think it would cause any problem, even when the constructor itself is generic. I'll add it to the RFC.

**Comment by Praetonus** [comment]
I think this should go into final comment period.

**Comment by sylvanc** [comment]
I'm hugely in favour of this. It will also make parameterised operators (e.g. things like `add[A](a: A)`) work much more nicely.

**Comment by jemc** [comment]
@Praetonus - can you send an email to the mailing list notifying of the final comment period?

**Comment by cquinn** [comment]
This is very nice. 👍

**Comment by Praetonus** [comment]
I think it's ready for vote.

**Comment by cquinn** [comment]
👍

**Comment by chalcolith** [comment]
:+1:

**Comment by Theodus** [comment]
:+1:

**Comment by sylvanc** [comment]
👍

**Pull request merged**
