### PR TITLE
move ReadBuffer and WriteBuffer

### PR DESCRIPTION
**Pull request by Theodus**

### CODE REVIEW

**Comment by SeanTAllen** [comment]
This is pretty non-controversial, it a pretty straight forward decision. @Theodus are you ready to move this to final comment period?

**Comment by Theodus** [comment]
@SeanTAllen yes

**Comment by jemc** [comment]
I don't know if I'm totally sold on the package name `buffered`, but I also don't have any specific suggestions to make at the moment.  Anyone have any ideas?

**Comment by SeanTAllen** [comment]
@Theodus don't forget the email to pony+dev.

**Comment by SeanTAllen** [comment]
@jemc yeah, i don't get a warm fuzzy from `buffered` but i have no better name. as long as @sylvanc doesn't name it, we'll probably be ok.

when in doubt, i name things `free-candy`.

**Pull request merged**
