### PR TITLE
FFI taming

### PR DESCRIPTION
**Pull request by dckc**
Apply a uniform taming policy to FFI in the pony standard library and document it as a best practice for the community. In brief, the policy is to "dominate" all impure FFI calls with AmbientAuth.

### CODE REVIEW

**Comment by SeanTAllen** [comment]
Can you walk me through the issues with something like Time.now() @dckc ?

**Comment by dckc** [comment]
OK... I'll give some thought to how to unpack the argument.

For level-setting: it's clear that `Time.now()` is not a pure function, right?

**Comment by dckc** [comment]
As I say, I intend to unpack the argument in a revision of the RFC, but meanwhile, in case you're in the mood, the most precise treatment I've seen for this stuff is:
- [Reasoning about Object Capabilities using Logical Relations and Effect Parametricity](http://www.eros-os.org/pipermail/cap-talk/2016-March/016762.html)

That's a March 24 cap-talk thread about a paper and presentation given by Dominique Devriese at the IEEE EuroS&P conference.

The paper explains:

> In the object capabilities model, effects can only be
> produced by sending messages to objects. These can be
> objects in the sense of object-oriented programming, but
> not necessarily so. Device objects are primitive objects that
> model resources in the outside world and produce effects
> in the outside world when receiving a message

A clock is such a device, and like I/O in haskell, reading is an effect just as much as writing.

**Comment by SeanTAllen** [comment]
So you believe that anything that isn't a pure function needs to have a capability?

**Comment by dckc** [comment]
That's a reasonable gloss of "effects can only be produced by sending messages to objects" so yes, not only do I believe it, but the authors of that paper and many others; as another example:

> All Authority Accessed Only by References. The authority an object has to affect or be affected the world outside of itself should be exactly represented by the references it holds. All primitives for interacting with the external world must be embodied by primitive objects, and one must obtain references to these primitive objects in order to exercise the associated primitive functions. Anything globally accessible must therefor be transitively immutable, otherwise it would constitute an unconditional source of authority not controlled by the reference-passing rules. -- [ode](http://www.erights.org/elib/capability/ode/ode-capabilities.html)

**Comment by SeanTAllen** [comment]
I don't see any real world utility in requiring Time.now() to be an async message send. I do see serious performance implications. Also major usability issues.

**Comment by dckc** [comment]
Async? Oh... I see how the "sending messages" terminology could be misleading. It's meant to be read in the smalltalk sense, where normal function calls are also message sends.

**Comment by SeanTAllen** [comment]
@dckc ah, yes that's a big difference. i'm on the sync call now. i'll go back and re-read later with that new understanding.

**Comment by SeanTAllen** [comment]
Closing as stale.

**Comment by dckc** [comment]
What deadline did I miss? This is still relevant, as far as I can tell. As of Aug 2016, you were going to go back and read it again.

**Pull request closed without merging**
