### PR TITLE
Type case for match

### PR DESCRIPTION
**Pull request by Perelandric**
This RFC defines a syntax for `match` expressions that allows a developer to define a case as a "type case". A type case is one where a value comparison is not desired and a variable assignment is not needed. The logic used in determining a matching type is the same as that of the `as` operator.

[Rendered](https://github.com/Perelandric/rfcs/blob/type-case-for-match/text/0000-type-case-in-match.md)

### CODE REVIEW

**Comment by jemc** [comment]
I think one potential point of contention with this RFC is the behaviour of giving access to the type-refined reference under the same name within the branch of the `match` block.  Arguably, this could be considered a kind of shadowing, and Pony has taken decidedly anti-shadowing stances on other issues.

That said, I'm not personally opposed to this aspect, and I think it makes sense from a "proof" point of view - within the branch of the `match` block, you know that a reference is refined to the given type, so you should be able to execute code that acts on that knowledge.

However, a possibly sticky example comes to mind with `var` references where the value can be reassigned.  Take a moment to think through the following example, decide whether it should compile okay or not, and consider what the type of `x` should be considered to be by the compiler at any given point in time:

``` pony
var x: (U64 | String) = 0
match x | as U64 =>
  x = x + 1
  x = "foo"
end
```

Granted, this example is contrived, but I think it highlights some potential problems with considering the type of `x` to be refined within the block.  Or maybe it doesn't.  But it's definitely behaviour we should define in this RFC.

(Note that compiler currently doesn't let you do things like `match | var x': U64 => ...` - you can only bind on `let` within a `match` block branch).

**Comment by Perelandric** [comment]
@jemc Thanks for your input. It is a departure from how Pony's type system works. I don't think it's a bad direction but I understand it wouldn't be without controversy.

WRT the `var` example, that's a good point and I'd say code should not compile because of the `"foo"` assignment since within that scope the `as` effectively makes it a `U64` in that scope. The increment of `x` as a `var` doesn't bother me so much since the compiler permits other outer scoped vars to be mutated, but I get your point.

I'll update the RFC later to reflect this in a little bit.

I'm curious, do you happen to know why `var` was dropped for match bindings? Only thing I could think of would be to perhaps accommodate case functions.

---

_Edit:_ While this may be a little bit of a stretch, it could be argued that there's _some_ precedence for refining the type of a variable by using the `as` operator.

``` pony
var x: (U64 | String) = "foo"

(x as String).lower()
```

Not exactly the same, but this is effectively refining `x` to be a String, albeit for only that moment. This could be seen as expanding on that concept.

**Comment by jemc** [comment]
> I'm curious, do you happen to know why `var` was dropped for match bindings?

No, I don't know, unfortunately - I'd be interested to know that as well, and I think it might impact the discussion of this RFC.

**Comment by Praetonus** [comment]
It looks like `var` for captures was dropped in [this commit](https://github.com/ponylang/ponyc/commit/323cb909c84f981b97363abd4974abbe96fe3ff8). Unfortunately, the reason isn't explained.

**Comment by SeanTAllen** [comment]
@Perelandric this seems to have stalled. anything you need to get it moving again that I might be able to help facilitate?

**Comment by Perelandric** [comment]
@SeanTAllen  I think it should remain stalled or be dropped. The main reasons are:
- It's non-essential
- It could probably be added later if desired
- It violates the principle of not having more than one way to do something

If someone else wishes to champion this, they certainly may, but I don't know that it's the best use of time at the moment.

**Comment by malthe** [comment]
The motivational example in the proposal could be rewritten as:

``` pony
let m = match n
| let n': USize => n'
| let n': String box => try n'.usize() else USize(0) end
end
```

That is, without introducing new variable names but leveraging that Pony allows the use of prime in variable names.

I think this illustrates that the current syntax is probably adequate.

**Comment by SeanTAllen** [comment]
n' is a new variable name

**Comment by malthe** [comment]
Yes, `n'` is a new variable name, but it's trivial to come up with as opposed to the example's `us` – and it's easy to read as a sort of "local, subtyped capture".

**Comment by SeanTAllen** [comment]
@Perelandric's point still applies. You are creating a variable you don't really want or need.

**Comment by Perelandric** [comment]
@malthe Yes, this isn't solving something that can't currently be done; it's just providing a nicer syntax IMO but at expense of _"two ways to accomplish the same thing"_ as noted in the drawbacks.

The somewhat clumsiness of the current syntax is evidenced in the [issue](https://github.com/ponylang/ponyc/issues/876) that I linked to in the "motivation" section. Naturally a prime (or multiple if required) can be used for better<sup>?</sup> naming, but as @SeanTAllen mentioned, it's the superfluous name itself that drives this RFC.

So ultimately, you're right. There are other ways to do this, which is why I suggested above that I think this should be at the bottom of the list, if on the list at all.

**Comment by Perelandric** [comment]
In the detailed design, I mentioned _"the rcap of the type must be a valid subtype of the original"_. Thinking about this now, that seems wrong unless the value would be implicitly consumed if, for example, we're going from `iso` to `ref` in that branch. I don't think that would be a good thing.

Unless someone has other thoughts on that, I'll remove that part.

**Comment by jemc** [comment]
In general, I'm inclined to see this RFC as desirable, but the parts of it that relate to using the same name as the matched type inside the branch seem like they will be difficult to implement, due to how the compiler passes currently work.  However there may be some kind of neat trick that can be applied to make it more feasible.

I think I'd like to have someone (possibly me, if I eventually get the time) take a crack at implementing this and see how it would work (and how much of an ugly and complicated hack it would be in the compiler) before I would approve of this RFC.

**Comment by SeanTAllen** [comment]
@jemc there's been no movement on this, what do we want to do?

**Comment by jemc** [comment]
I'd still like to see this change happen, but I expect it won't be easy until we do a rewrite of the typechecker to use a kanren-style of constraints. Unless anybody has a clever idea about how to do this. I suspect it would be similar to how `iftype` works, but `iftype` is still a bit buggy.

**Comment by SeanTAllen** [comment]
Closing as stale.

**Pull request closed without merging**
