### PR TITLE
Unique promises

### PR DESCRIPTION
**Pull request by Praetonus**
[Rendered](https://github.com/Praetonus/rfcs/blob/unique-promise/text/0000-unique-promise.md)

### CODE REVIEW

**Comment by SeanTAllen** [comment]
There's nothing right now that really teaches promises. I think as part of adding anything to Promises that we need to come up with a decent strategy for teaching them.

**Comment by SeanTAllen** [comment]
What are the situations where we would want to be able to send iso's as part of a Promise?

**Comment by Praetonus** [comment]
To teach promises, maybe a Pony pattern would be good?

Getting `iso` from promises can be useful when we want to mutate the result during/after the promise chain.

**Comment by SeanTAllen** [comment]
I think we need a chapter in the tutorial on Promises as a minimum.

I don't really follow the mutate results during/after. When would you want to do that? Can you give examples of situations where that is needed and/or desire-able? I understand this in theory but code demonstrating the value would be great.

**Comment by SeanTAllen** [comment]
Another question. The argument so far for this is to allow mutable values from a promise but, this allows for tag and val as well. If the only reason for this is mutability then it shouldn't be allowing any sendable item. If allowing val and tag has value here then we need to be able to teach people when to use Promise vs Unique Promise which needs to be addressed as part of the RFC.

**Comment by Praetonus** [comment]
A (quick and unpolished) example of this could be a database ORM package. Asynchronous queries would return objects via promises. These objects need to be mutable to allow modifying them directly and committing the modifications into the database.

Regarding `iso` vs `#send`, I've put `#send` here because it was possible. Allowing `val` and `tag` doesn't add anything so I'm not opposed to restricting unique promises to `iso` if it reduces confusion and collisions in promises vs unique promises use cases.

**Comment by SeanTAllen** [comment]
@Praetonus Can you provide example code? I think example code for how this would be used is very important to the RFC. Example code of different use cases will help greatly clarify.

**Comment by Praetonus** [comment]
Here's the simplified [ORM example](https://gist.github.com/Praetonus/915c4e7eede703b874d67d2d83963b08). The promise is used with asynchronous queries and not with behaviours but this is still a form of message sending so this would be the same principle with pure Pony idioms.

Additionally, I have some more thoughts on `iso` vs `#send`. With `iso` only, you can't do things like this:

``` pony
let lbd = recover lambda(x: MyObj iso) =>
  dosomething()
end

uniquepromise.next[None](consume lbd)
```

Since `None` is always `val`, we can't use it for convenience in `next` when using lambdas or functions returning `None`. I think this is a serious drawback because the user will have to return an isolated useless object from every function filled by an unique promise.

**Comment by SeanTAllen** [comment]
Does a promise rather than a notifier make sense in the context of the ORM example? It feels odd compared to the normal notification pattern that is normally used for async operations of that sort.

With the iso vs #send example of None you give, that is an interesting point. I feel like there is a core of an idea but it needs to be fleshed out. I'm still grasping at the ramifications of it and how we would explain to people when to use which type of promise or if it should be two different kinds of promises rather than something about how you set them up.

Another question, can I mix and match Promise and UniquePromises together if they are in fact different types of actors?

**Comment by Praetonus** [comment]
I think a promise makes sense here since it is a request/response pattern and not random exterior events you are notified of.

It should be possible to chain promises after unique promises and conversely. This would be good, I'll have to think about the implementation.

**Comment by SeanTAllen** [comment]
@Praetonus could this be additional methods on the existing Promise or does it need to be a different types?

**Comment by SeanTAllen** [comment]
@Praetonus any updates to this?

**Comment by jemc** [comment]
For whatever it's worth I've been thinking more about promises lately.  I think we need to try to come up with a generic interface for promises to be interoperable with eachother.  Not only is there the distinction between `Promise[A]` and `UniquePromise[A]`, but I've also seen a need to have a promise that returns an `Error` object instead of raising an anonymous `error` (so, `OtherPromise[A,E]`).  It would be great if we had a common interface so that all of these (including other kinds of promises a user might create) were interoperable to the greatest extent that makes sense (basically, being able to chain them to eachother).

**Comment by Praetonus** [comment]
I think the [generic subtyping](https://github.com/ponylang/rfcs/pull/62) could help solve the common interface and chaining problems. I'll come back to this RFC after the other one is implemented.

**Comment by patternspandemic** [comment]
As a new user of Pony, and when I hadn't understood the capabilities requirement of the existing promises API (#share), I tried to use it with the intention of fulfilling a promise with an iso object. Obviously this didn't work out for reasons I now understand, but it may be interesting to note that I attempted to use it in a way that a UniquePromise would allow.

I solved my problem by fulfilling the promise with the shareable data from which I could construct the objects I needed. Basically instead of creating and fulfilling with the object, I created the object inside a fulfillment handler, and passed it along via a behavior call on an actor closed over by the handler.

**Comment by SeanTAllen** [comment]
@Praetonus Should this RFC be closed?

**Comment by SeanTAllen** [comment]
Closing as stale.

**Pull request closed without merging**
