### PR TITLE
Add RFC for embedded actors.

### PR DESCRIPTION
**Pull request by jemc**
[Rendered](https://github.com/jemc/pony-rfcs/blob/embed-actor/text/0000-embed-actor.md).

### CODE REVIEW

**Comment by SeanTAllen** [comment]
@jemc I think this could work well hand in hand with "asynclambda" to address a lot of pain points we've hit at Sendence. I'll get that written up sometime after I get back from vacation (aka post October 9).

**Comment by SeanTAllen** [comment]
This probably results in a fairly decent chunk of new code, I think its reasonable to note the carrying cost of that code as a drawback.

Additionally, I would expect this change to introduce a lot of instability and bugs that we would be chasing for a while, I think its worth noting that as well.

**Comment by SeanTAllen** [comment]
I find the overhead of cross actor messaging that you highlight very familiar. In the first versions of our application, user defined computations can in their own actors, however the overhead was considerably. We've since come up with rules that allow us to put multiple computations within a single actor. This has been a big performance boon for us. We were able to do this because those computations where defined as actors. I think that the goal of lowering that overhead for actors is quite laudable.

**Comment by SeanTAllen** [comment]
I think people can rightly raise the following alternative:

You could accomplish this by putting the functionality you want to embed in a class which can then be used by various different actors.

Its a fairly valid alternative except, it falls apart in the case of ASIO events that have to be delivered to an event on an actor.

Another alternative would be to allow both classes and actors to receive messages. There are actor systems where this is how it operates. Sylvan and I have recently discussed the value of making Pony work in that fashion (there are many and "asynclambda" that I need to write up a RFC for is a step in that direction).

I think within how Pony currently works, none of the alternatives make sense however, I think before this goes to final comment that it makes sense to devote a special additional meeting of an hour or two for a conversation about the pain points you have experienced that this addresses and the pain points I've experienced that asynclambda addresses and see if there is a more holistic, deeper change to Pony that would be better for addressing both. I would say we have this meeting separate from the regular sync, allot 60 to 120 minutes and make sure it includes at least you, me and @sylvanc plus anyone else from the community who wants to be involved.

I think we've both experienced different problems with Pony's composition and messaging models and it behooves us to look at them at a global level and not just individually in two RFCs designed to address different aspects of what is perhaps a single larger problem.

**Comment by SeanTAllen** [comment]
@jemc a question for clarification: if I call a behavior on an embedded actor, that would happen asynchronously, correct?

**Comment by jemc** [comment]
@SeanTAllen I've added the drawbacks and alternatives you mentioned, thanks.

> it makes sense to devote a special additional meeting of an hour or two for a conversation

I would definitely welcome such a conversation - I think it would be a good idea.

> if I call a behavior on an embedded actor, that would happen asynchronously, correct?

Correct.  From a scheduler perspective, it would be just like calling an actor calling a behaviour on itself, which is also asynchronous.  The extra power would come in the fact that the inner actor could expose a synchronous API as well as an asynchronous one.

**Comment by jemc** [comment]
We discussed on the sync call that there are some technical feasibility concerns related to how actor message queues and dispatch currently works, so this would either require a creative solution on that end, or it would be infeasible.  I'm going to leave the RFC open for a bit, because I want to try to investigate some creative solutions for that, but it may prove futile.

The main alternative discuessed was the first one in the RFC, do nothing different in the language, but encourage actors (like `TCPConnection`) to be written as classes that handle most of the functionality, but are wrapped in a thin layer of actor by the library, and potentially also by the user in a custom actor.  This is not necessarily ideal, given that it requires extra types for no reason other than extensibility, and does nothing to help with actors in libraries that you do not control.  I'm going to investigate in parallel what a synchronous `TCPConnectionCore` might look like.

**Comment by Praetonus** [comment]
I've been thinking about the implementation side of the RFC and I might have found a solution with little overhead.

We could adapt the selector painting algorithm used for the vtable IDs to work for message IDs. It would allow us to make sure that the message IDs for a given actor and the message IDs for its embedded actors never overlap. Then the dispatch function for the enclosing actor would simply have to partition the possible IDs and dispatch to the right actor.

The sending side is a little more complicated. I think the most straightforward way is to add the enclosing actor's address in embedded actors and to use that address in the message sending functions, if the actor is indeed embedded. It would probably be possible to add that only on actor types that can be embedded so that there is no overhead on actor types that are never embedded.

**Comment by jemc** [comment]
> It would probably be possible to add that only on actor types that can be embedded so that there is no overhead on actor types that are never embedded.

If I had an actor that embedded a `TCPConnection`, for example, does that mean that every instance of `TCPConnection` in the program would have to pay the cost of checking whether it is embedded or not?

**Comment by Praetonus** [comment]
Yes. But I expect it would be possible to make that cost very low, for example by setting some of the low bits of the actor's address. That might interfer with proxy actors in distributed Pony so it would need to be implemented with that in mind.

I also think it would be possible to remove the check when a given actor type is always embedded and is never used in an interface with non-embedded actors. That might have a high impact on compilation times, though.

**Comment by jemc** [comment]
If the design I proposed in https://github.com/ponylang/rfcs/pull/91#issuecomment-306005552 gets accepted as the design for #91, I'll close this one, as my motivating use case for this RFC will have been fulfilled.

**Comment by Praetonus** [comment]
In case we still want to pursue this RFC, I think I've found a way to send messages to embedded actors with no overhead.

The basic idea would be to change the runtime layout of an actor to include pointers to the message queue and to the heap. For an embedded actor, these pointers would refer to the fields of the enclosing actor.

Then, when sending a message or allocating heap memory, we'd always dereference the pointers instead of accessing the fields directly.

In order to avoid additional cache misses, the pointers should be placed next to their respective fields. Also, this approach would mean that the pad for embedded actors is mostly unused memory.

**Comment by SeanTAllen** [comment]
Closing as stale.

**Pull request closed without merging**
