### PR TITLE
Subtype checking

### PR DESCRIPTION
**Pull request by Praetonus**
[Rendered](https://github.com/Praetonus/rfcs/blob/subtype-checking/text/0000-subtype-checking.md).

### CODE REVIEW

**Comment by jemc** [comment]
@Praetonus - thanks for taking the time to write this up.  I like your choice of syntax, and I don't disagree with anything in the proposal.

---

Would it be possible to create an `iftype`-guarded method that has no default implementation?  That is, the method would only be a part of the type when the guard clause held true.  This seems desirable to me, but it's not immediately clear if it would cause other problems in the type system.

**Comment by Praetonus** [comment]
> Would it be possible to create an iftype-guarded method that has no default implementation? That is, the method would only be a part of the type when the guard clause held true. This seems desirable to me, but it's not immediately clear if it would cause other problems in the type system.

Yes, I talk about it in the specialised functions section. I think I'll reword that section a little bit because the vocabulary isn't consistent currently.

**Comment by jemc** [comment]
Thanks, that change does make it clearer. :+1:

**Comment by malthe** [comment]
It seems to me that unless you're matching on a specific type then the compiler won't be able to work around dynamic dispatch.

In the case of `String.append`, wouldn't it be good enough if you could tell the compiler to specialise the method for the two types `String box` and `Array[U8] box` – ?

Alas, this is something you get for free with a JIT-compiler.

**Comment by malthe** [comment]
This might be an alternative syntax. Example taken from https://github.com/ponylang/ponyc/pull/1360.

``` pony
fun clone(): Array[this->A!] iso^ where A <: Any #send
```

It's a reuse of `where` but I think it's possibly easier to read and definitely say.

**Comment by jemc** [comment]
@malthe - the motivation for using `iftype` is again the pesky LL(1) grammar requirement - it is a marker that lets the parser know what's coming next.  There is some discussion about this in the original ticket that formed the basis of this RFC: https://github.com/ponylang/ponyc/issues/683

However, after playing with the parser a bit last night I think it might be possible to parse `<:` in the grammar just like any other infix operator (without compromising LL(1)), then impose limits in the `syntax` pass for what is possible to put on the left hand side and right hand side.  I'll investigate a bit more and report back here.  If we can make it work, then we can indeed avoid adding the `iftype` keyword, and use the `<:` operator in "normal" (value-oriented) `if` statements and function guards.

``` pony
if A <: B then
  // Generate this block if A is a subtype of B.
  // A is constrained to B in this block.
else
  // Generate this block otherwise
end
```

**Comment by Praetonus** [comment]
> It seems to me that unless you're matching on a specific type then the compiler won't be able to work around dynamic dispatch.

Yes, this will only be applicable when the program has some static informations about subtyping. But I think this is the common case, for example you rarely call `String.append` with a `ReadSeq`, you generally have a concrete object like a `String` or an `Array[U8]` to pass to the function.

> In the case of String.append, wouldn't it be good enough if you could tell the compiler to specialise the method for the two types String box and Array[U8] box – ?

An hypothetic implementation of `String.append` with that feature could be

``` pony
fun ref append[A: ReadSeq](seq: A, ...): String ref^ =>
  iftype A <: (String box | Array[U8] box) then
    // Fast append for byte sequences.
  else
    // Generic append for other stuff.
  end
```

That kind of function would be much more convenient to use once generic type inference is in.

> _`where` syntax_

IIRC, the syntax for guards was changed from `where` to `if` a while ago. I used `iftype` here mainly for consistency with other guards.

> However, after playing with the parser a bit last night I think it might be possible to parse <: in the grammar just like any other infix operator (without compromising LL(1)), then impose limits in the syntax pass for what is possible to put on the left hand side and right hand side. I'll investigate a bit more and report back here. If we can make it work, then we can indeed avoid adding the iftype keyword, and use the <: operator in "normal" (value-oriented) if statements and function guards.

I thought about that too but I don't think it would be good. Since `<:` can change the generated code, we can't treat the result as a plain boolean. The `iftype` block is a straightforward way to make sure that no runtime value will interfere. With a standard `if` block, we'd have to add lots of verifications and that would be error prone.

**Comment by jemc** [comment]
> I thought about that too but I don't think it would be good. Since `<:` can change the generated code, we can't treat the result as a plain boolean. The `iftype` block is a straightforward way to make sure that no runtime value will interfere. With a standard `if` block, we'd have to add lots of verifications and that would be error prone.

You're right, those are good reasons to stay away from that line of approach.

**Comment by Praetonus** [comment]
I've amended the RFC to allow things like this

``` pony
// C2 <: C1

fun foo() iftype A <: C1
fun foo() iftype A <: C2
```

The most specialised function (i.e. the one with the most specific subtype in the constraint) will be used, but there must be an appropriate subtyping relationship between the function types.

This is a generalisation of the default case, as `fun foo()` is the same thing as `fun foo() iftype A <: Any`.

**Comment by jemc** [comment]
@Praetonus - good call.  This will allow for useful things like:

``` pony
fun foo() iftype A <: Integer[A]
fun foo() iftype A <: Any #share
fun foo()
```

**Comment by malthe** [comment]
I don't think the `issubtype` operator is really necessary for what the proposal motivates. Is there something in the way for just having:

``` pony
fun foo(): C iftype A: Integer[A] =>
```

That is, to use the same semicolon as we already use in generics and use `iftype` only to impose a type constraint per-method.

I don't see how the following `iftype` avoids dynamic dispatch:

``` pony
iftype A <: (String box | Array[U8] box) then
  // Fast append for byte sequences.
else
  // Generic append for other stuff.
end
```

How can that be "fast" if the compiler anyway has to operate on A using dynamic dispatch due to there being a union of two types?

**Comment by jemc** [comment]
@malthe - the principle motivation of this RFC is not to avoid all dynamic dispatch - it is to provide specialized implementations of generic methods that are resolved when the generic type is reified.

To use your same example, this RFC will allow us to do this (note that I've expanded the comment to be more explanatory of what will be going on):

``` pony
iftype A <: (String box | Array[U8] box) then
  // Fast append for byte sequences, using memcpy with the underlying pointer.
else
  // Generic append for other stuff, pushing bytes one-by-one in a loop.
end
```

Instead of this:

``` pony
match seq | let seq': (String box | Array[U8] box) =>
  // Fast append for byte sequences, using memcpy with the underlying pointer.
else
  // Generic append for other stuff, pushing bytes one-by-one in a loop.
end
```

Both examples allow us to specialize and use `memcpy` when we have a type that exposes a pointer to a contiguous chunk of memory.  The difference is that one case will specialize at compile time (when the method is reified) and the other will specialize at runtime (forcing a `match` cost every time the function is executed).  This is a winning scenario for performance, but the only catch is that we have to have the sufficiently specific type passed in as a type parameter (`A`) in order for it to work.

> I don't think the `issubtype` operator is really necessary

There is no `issubtype` keyword in the RFC, so not sure what you're talking about here.

**Comment by SeanTAllen** [comment]
In case I haven't mentioned, I very very much want this feature. This would be huge for us with our application where we are paying that match cost a ton.

**Comment by Praetonus** [comment]
@malthe Like @jemc said, since `A` is a generic type, the function is fully reified at compile-time with the concrete type, as if you wrote the function with e.g. `String` everywhere `A` appears. That means if we call the function with `String`, we will call `String.cstring()` directly, and not `(String box | Array[U8]).cstring()`.

The constraint of a generic is purely a compile-time concept for type checking, it doesn't mean we'll use the vtable of the constraint at runtime.

**Comment by Praetonus** [comment]
> There is no issubtype keyword in the RFC, so not sure what you're talking about here.

I think @malthe is talking about `<:`.

Yes, it would be conceivable to use `:` for consistency. We could also use `<:` everywhere, including in the existing constraints, since `<:` is used in several languages (and in the Pony tutorial) to denote subtyping. That would break a lot of existing code, though.

**Comment by jemc** [comment]
I'm in favor of keeping `<:` as this RFC currently describes, rather than using `:` for the new `iftype` conditions.  I think `<:` reads quite well when read as "is a", and I also think it would be better not to continue overloading new meanings on the `:` symbol.

I would also be in favor of using `<:` to specify type parameter constraints.  As you mention this would break code, but I think it would be more consistent and more readable overall.  However, I think it would be better to scope this effort in a different RFC.

**Comment by malthe** [comment]
@jemc, thanks – now I get it. I think what I had somehow missed is that of course the `iftype` operator only restricts on the reified generic type or types.

**Comment by jemc** [comment]
@Praetonus want to go to final comment period on this?

**Comment by Praetonus** [comment]
@jemc I'd like to resolve the question about `A :< B` always true/false resulting in a compilation error before going into final comment period. Being able to identify redundancy would be good but it might prove frustrating to users when their otherwise valid code is deemed suboptimal by the compiler.

**Comment by Praetonus** [comment]
Actually, since type checking is fully done before reification, the programmer doesn't know less than the compiler about subtypes and can easily figure out what's wrong. So maybe that's not a problem after all.

**Comment by Praetonus** [comment]
Since nobody raised an argument against this, I'm going to amend the RFC and put it into final comment period.

**Comment by Praetonus** [comment]
After giving it some additional thoughts, an error when `A :< B` is always true doesn't seem right. It will basically forbid the use of the function with every subtype of `(B & [constraint of A])`. I'll remove that.

The always false part is fine since it depends only on `B`, which can't be generic.

**Comment by jemc** [comment]
This looks to be ready for a vote tomorrow, so I'm switching the label.

Please speak up if it's not actually ready for some reason.

**Comment by Praetonus** [comment]
Looks like I forgot to update the RFC with what I said above. I've updated it. It's probably still ready for vote since it is a minor change.

**Comment by SeanTAllen** [comment]
@Theodus i'm really busy right now, can you create the issue for this?

**Pull request merged**
