### PR TITLE
Guidelines for source file names in the standard library.

### PR DESCRIPTION
**Pull request by jemc**
[Rendered](https://github.com/jemc/pony-rfcs/blob/file-naming-guidelines/text/0000-file_naming_guidelines.md).

### CODE REVIEW

**Comment by SeanTAllen** [comment]
I prefer `-` to `_` in file names but, I'm good with this. +1 to this RFC.

**Comment by hibnico** [comment]
I really like the idea of mapping the types declared in a file and the file name. I often struggle with that reading the standard library code.

Then, is there a rationale for the file name to be snake cased rather than camel cased ?

Maybe it is my long years of Java coding which makes me biased, but I find really no brainer to search of a type and just look for a name.ext. I needs a mental transformation. And it can be painful if the tools doesn't support that transformation. For instance, if I am reading some code, there is some type I don't know about, I would really like to just copy the name and make my favorite editor search for that name + "*.pony". Having to transform the name to a snake cased one would be painful.

Also, not sure yet if it is a good pattern for the standard library, but I have found that it works great where files which contain main types are camel cased, and for the files which contain no particular principal type, I just use a lower case name which tries to describe what's in there. See for instance that package:
https://github.com/nlalevee/pony-mysandox/tree/master/src/async_compute

**Comment by malthe** [comment]
I prefer "" to "_", e.g. `contentslog.pony`.

It's true that this makes a module that map to a private principal type unrecognizable but it can be argued that top-level private classes shouldn't be principal (e.g. `_ClientConnection` from the proposal).

The fact that the underscore syntax, e.g. `contents_log.pony` follows the method naming convention is a bad thing in my view. And the underscore syntax is not sufficient anyway for a machine to convert the name to a camel-case class name. For example, `ssl_connection` can't be trivially turned into `SSLConnection`.

**Comment by jemc** [comment]
> is there a rationale for the file name to be snake cased rather than camel cased?

I think the only rationale would be that files with uppercase letters tend to be uncommon in most source trees, but this is a pretty weak one.  I think I could be easily convinced to follow the convention of using the exact name of the principal type for the file name, case included (for example, `ContentsLog.pony` and `_ClientConnection.pony`.  I would probably +1 that idea, but I would expect others to be a bit more resistant - maybe I'm wrong, though.  It would be interesting to hear others' thoughts on that.

> it can be argued that top-level private classes shouldn't be principal

If there are no public types in a file, and we can't consider private types to be principal types, then how would we name the file?  If we name the file after something else (I have no idea what), then how do we find the file that defines a given private type when looking for it?  Some private types (like `_ClientConnection`) are extensive and important, and in my opinion there's no reason to suggest they can't be principal types.

**Comment by malthe** [comment]
@jemc, Java has inner classes which arguably have pretty good utility as _strategies_ or _behaviours_ used internally in a method. But I think principal private classes are mostly an anti-pattern. We need to be able to understand what objects are in the system and putting an underscore in front of it is like a big warning sign saying "no access".

**Comment by hibnico** [comment]
@malthe if we should compare to Java, since in Pony the file has no visibility meaning then private class in Pony are the Java class with default package visibility. So even in Java a principal type of a file may not be exposed in an API, not useable for third party code.
Also, the discussion here is just about a file name convention, not rules for an API design. I "just" see it as an improvement of browsing code.

**Comment by SeanTAllen** [comment]
@jemc i think this is ready for final comment, agree?

**Comment by jemc** [comment]
Sure, let's do that.

For the record, I think the main remaining point of disagreement is about the word separation formatting in file names.  We've got advocates for the following options:
1. `contentslog.pony`
2. `contents-log.pony`
3. `contents_log.pony` (my preference, and the one currently described in this RFC)
4. `ContentsLog.pony`

I think we should try to come to some consensus here within the comment period (or, if necessary, at the end when we vote).

For the record, I actually really like option 4 due to its simplicity and consistency with the type name (I think I even like it better than option 3), but I see it as being controversial for others (maybe I'm wrong?) due to the relative uncommonness of using uppercase letters in file names.  Option 1 is my least favorite, because there is no indication of word separation at all, but it is the closest to what we have now, so that's worth noting.

**Comment by SeanTAllen** [comment]
I prefer 2 but find 3 to be completely reasonable and don't feel strongly enough to argue for 2.

I dislike 4 because of annoying issues on OSX with case sensitivity or lack thereof. Whenever I start using capital letter in source code file names on OSX eventually some sensitivity edge case crops up. Thus a preference for 1 to 3 over 4.

In general my top 2 are

3 and 2

followed by

4

followed by 

1

**Comment by Theodus** [comment]
I personally prefer 2, but 3 is a close second.

**Comment by SeanTAllen** [comment]
ready for final vote on this @jemc ?

**Comment by jemc** [comment]
@SeanTAllen - close, but one more question:

@Theodus, @SeanTAllen, since you both said you prefer 2 - I was about to change the RFC to reflect this, but the question hit me - what about the case of the private principal type?  The RFC advocates for distinguishing these with a preceding underscore to match the one on the type, but it's not clear how this would look to me in a "dasherized" scheme.  That is, I'm having trouble liking either `_client-connection.pony` or `-client-connection.pony`, and I think that's a good reason to prefer underscores over dashes (so that we avoid a mixture or a conflation of underscores and dashes).  Any other ideas?

**Comment by SeanTAllen** [comment]
i find dashes to be of a more civilized age.

but i'm good with _ as many languages do that.

**Comment by Theodus** [comment]
The underscoreat the beginning would be my preference for sure.

**Comment by jemc** [comment]
@Theodus - so `_client-connection.pony`?  I don't really know if I can bring myself to like that.

**Comment by Theodus** [comment]
@jemc, I got two other opinions and they both agreed with you, so I suppose the dash is more appealing.

**Comment by jemc** [comment]
But I'm still saying `_client_connection.pony` - so I don't see how you're agreeing with me! :ghost:

**Comment by Theodus** [comment]
Like I said, that option was a close second.

**Pull request merged**
