### PR TITLE
Add String.add iso proposal

### PR DESCRIPTION
**Pull request by ergl**
[Rendered](https://github.com/ergl/rfcs/blob/f4ff73f24d0f2dd25e77c1b1e0dda5cb50b4a825/text/0000-string-add-iso.md)

For more context see also the [Zulip discussion](https://ponylang.zulipchat.com/#narrow/stream/189985-beginner-help/topic/String.20add.20method.20return.20type) where this was raised.

### CODE REVIEW

**Comment by SeanTAllen** [comment]
I'm in favor of this change.

**Comment by jemc** [comment]
This RFC was approved in today's sync call.

**Comment by SeanTAllen** [comment]
@Theodus when you have time, can you do the dance for this RFC?

**Comment by Theodus** [comment]
> @Theodus when you have time, can you do the dance for this RFC?

Sure, I'll take care of it later today

**Pull request merged**
