### PR TITLE
Class and Actor Field Docstrings

### LINKED ISSUE #106: Add docstrings for class/actor members
Optionally allow docstrings for class/actor fields below or above the field definition.

```pony
class MyClass
  """class docstring"""

  let number: U32 = 1
  """field docstring below"""
  
  fun method(arg: String): None =>
    """method docstring"""
    None
```

```pony
class MyClass
  """class docstring"""

  """field docstring above"""
  let another_number: U32 = 1
  
  fun method(arg: String): None =>
    """method docstring"""
    None
``` 

I would like your opinion on this. Maybe a kind of a vote, `No`, `Above` or `Below`?

### PR DESCRIPTION
**Pull request by mfelsche**
[Rendered](https://github.com/ponylang/rfcs/blob/field-docstrings/text/0000-class-actor-fields-docstrings.md)

fixes #106

### CODE REVIEW

**Review by jemc — APPROVED** [review]

**Comment by SeanTAllen** [comment]
@mfelsche are there drawbacks to this? alternatives?

**Comment by mfelsche** [comment]
@SeanTAllen not really. The only drawback i see is slightly increased AST size. There is no real acceptable alternative (putting the string before the field is ambiguous syntactically, putting field information into the class/actor docstring is unacceptable for me)

**Comment by SeanTAllen** [comment]
@mfelsche that's a drawback. additional code to support is a drawback.

I think its important to elaborate on alternatives and their basic pros and cons. 

You've done a lot more thinking on the subject, can you please add more information in those sections?

**Comment by mfelsche** [comment]
@SeanTAllen right. i added drawbacks and alternatives.

**Comment by Theodus** [comment]
@mfelsche is this ready to enter final comment period?

**Comment by mfelsche** [comment]
@Theodus From my side yes. 

But according to the process the actual condition is that there are no opponents to this RFC and it has been discussed properly (if needed). Are there any opponents?

**Comment by SeanTAllen** [comment]
@mfelsche mark as "final comment period and send an email to the mailing list"

**Pull request merged**
