### PR TITLE
Drop "then" from "try/else" clause

### PR DESCRIPTION
**Pull request by malthe**
Drop "then" clause from "try/else" clause – see [proposal text](https://github.com/malthe/rfcs/blob/try-else-and-drop-then/text/0000-try-else-and-drop-then.md).

See [PR #9](https://github.com/ponylang/rfcs/pull/9) for an extended conversation on the topic.

### CODE REVIEW

**Comment by SeanTAllen** [comment]
@malthe you removed sections from the RFC, for example "how do we teach this".

As part of the removal of the feature I think in "how do we teach this", we need to have a strategy for communicating the change and what if any existing documentation will need to be changed.

**Comment by malthe** [comment]
@SeanTAllen, added.

**Comment by SeanTAllen** [comment]
@malthe which documentation? tutorial? or something else? are there materials/examples etc that need to change because of this?

I'm in favor of this but I think it behooves us to know what needs to be updated so that when a PR arrives we can make sure we don't have dangling documentation etc.

**Comment by malthe** [comment]
@SeanTAllen I have added a note that the relevant [Try-then blocks](http://tutorial.ponylang.org/expressions/exceptions.html#try-then-blocks) documentation section can be removed.

I couldn't tell how much the construct is used in the repository. I think the easiest is to simply remove the parser code that implements the syntax and have the compiler list the errors. This is a to-do that should be done before we move this RFC into the final stage I think.

**Comment by SeanTAllen** [comment]
@malthe are you ready to move this to final comment period?

**Comment by Perelandric** [comment]
If the `then` would run in the case where the code in the `else` errored or returned, it would feel a little like a more flexible version of Go `defer` in that it isn't bound to the entire function body. Then again, if that behavior is desired, a different construct that doesn't _require_ a potential error may be better.

**Comment by jemc** [comment]
> a different construct that doesn't require a potential error may be better.

@Perelandric - that's more or less what we discussed on the last call where we talked about this - the concept is somewhat orthogonal and could use its own form that isn't tied to `try`.

**Comment by malthe** [comment]
@SeanTAllen, I think it's ready but I wanted to get an idea of the extent to which the "then" clause is used in the current codebase (standard library and/or examples) and tried removing the parse rule from ``parser.c``. But even I try to also remove ``then_clause`` from the various calls to ``ast_get_children`` I always get an assertion error: ``Assertion 'p != NULL' failed``.

**Comment by SeanTAllen** [comment]
@malthe ok. let me know when you feel this is ready to go into final comment period by dropping an @ here.

**Comment by SeanTAllen** [comment]
This seems to have staled. Is there any reason @malthe not to take this to final comment period?

**Comment by malthe** [comment]
@SeanTAllen – yes and no: the difficulty is that actually implementing this change is not so straight-forward since `with` is implemented as sugar that uses `then` to dispose its objects.

But the good news is that `then` is not currently used anywhere in the standard library, so it should be relatively smooth sailing once removed.

The reason this RFC has stalled is that ideally we would first have a general `defer` statement that we could use to implement `with` and then be free to remove `then` from `try`.

Or alternatively somehow disable `then` from direct usage so that it's just used as an implementation detail. I couldn't figure out how to do that in a better way than renaming it to e.g. `then_disabled` or `__then`.

**Comment by SeanTAllen** [comment]
@malthe i think with input from @Perelandric, @jemc and maybe @sylvanc we should be able to get this to a place where we have an agreed upon solution that could be voted on even if it isn't immediately implementable.

**Comment by sgebbie** [comment]
In addition to dropping `then` from `try...else...then..end` maybe a construct like:

```pony
after
  // some block
always
  // code that is executed irrespective of `error`
end
```

Might be useful? Then one could in theory write:

```pony
after
  try
    h.assert_true(FileInfo(tmp)?.directory)
  end
always
  h.assert_true(tmp.remove())
end
```

Or even the follow "partial" code:

```pony
after
  h.assert_true(FileInfo(tmp)?.directory)
always
  h.assert_true(tmp.remove())
end
```

**Comment by SeanTAllen** [comment]
Closing as stale.

**Pull request closed without merging**
