### PR TITLE
Non-blocking DNS

### PR DESCRIPTION
**Pull request by malthe**
[Rendered](https://github.com/malthe/pony-rfcs/blob/non-blocking-dns/text/0000-non-blocking-dns.md)

### CODE REVIEW

**Comment by aturley** [comment]
@malthe can you change the title to something like "Non-Blocking DNS"? That will make it easier to identify from the list of pull requests.

**Comment by SeanTAllen** [comment]
"This will require some minor changes to network test code" isn't really how we will test.

How exactly will we test this?

## 

How will we teach... 

What documentation exactly should be updated?

## 

Alternatives:

Leave as is.

## 

Re: detailed design,

I'd like to see actual implementation details. Some implementations would be no better than the existing (spawning a different actor that blocks doesn't do us any good), a thread pool for just this is problematic for thread pinning. The implementation details are critically important here.

**Comment by malthe** [comment]
With regards to implementation details, should I go forward with suggesting an own implementation in Pony, or incorporate one of the existing C-libraries that implement their own DNS resolver.

Should we aim for full platform parity or might some platforms be left with a "no better than the existing" solution?

**Comment by SeanTAllen** [comment]
Closing as stale.

**Pull request closed without merging**
