### PR TITLE
String split zero copy

### PR DESCRIPTION
**Pull request by malthe**
[Rendered](https://github.com/malthe/pony-rfcs/blob/string-split-zero-copy/text/0000-string-split-zero-copy.md)

Implementation is here: https://github.com/malthe/ponyc/compare/issue-1309...malthe:string-split-zero-copy

### CODE REVIEW

**Comment by jemc** [comment]
Can you make explicit the method signature of the current `String.split` method as it compares to the new one?

**Comment by SeanTAllen** [comment]
I need convincing. I can see having another split method that does this. We have/had that at Sendence. However changing split to only work on vals is not a good thing. Its perfectly reasonable for me to want to be able to split a ref. This change would disallow that. Rather than changing the existing method, I believe what you want is a new method.

**Comment by malthe** [comment]
I suppose with subtyping it would be quite easy to provide two implementations of `String.split` – one for `val` and one for `ref`.

**Comment by SeanTAllen** [comment]
What subtyping are you referring to @malthe?

**Comment by malthe** [comment]
I was thinking that with https://github.com/ponylang/rfcs/pull/62 it might be possible to "overload" `String.split` with two implementations.

If that's something we want?

An alternative is of course to go with different names but that seems a bit wrong to me – like Hungarian notation almost.

I think ergonomics should be a concern here as well as obviously performance.

**Comment by jemc** [comment]
I wonder how the performance of `(String box).clone -> (String val).split` compares to the current case of `(String box).split`.  It's possible that the `clone.split` would actually be _more_ performant, since it involves one large buffer allocation instead of many small buffer allocations.  If that ends up being true, I'd think that there is not much justification to keep `(String box).split` around.

It would be interesting to see some benchmarks.

**Comment by SeanTAllen** [comment]
@jemc that would be an interesting benchmark.  did you mean:

`(String box).split` in the following?

> I'd think that there is not much justification to keep (String box).clone around.

**Comment by jemc** [comment]
@SeanTAllen yes, thanks for the correction - I've corrected the comment.

**Comment by malthe** [comment]
The benchmark results are:

```
split               20    82373935 ns/op
split-zc            30    44659338 ns/op
```

For what it's worth, https://github.com/ponylang/ponyc/pull/1335 actually runs about 1% faster than `"split"`.

Program code:

``` pony
use "ponybench"

actor Main
  let length: USize = 1024 * 1024

  new create(env: Env) =>
    let s = recover ref String.create(length) end

    while s.size() < length do
      s.append("abcde ")
    end

    let s': String val = s.clone()
    let bench = PonyBench(env)

    bench[None]("split", recover val lambda()(s') => s'.split() end end)
    bench[None]("split-zc", recover val lambda()(s') => s'.clone().split_zc() end end)
```

**Comment by jemc** [comment]
@malthe thanks for doing this benchmark.

I cloned your fork and tried a few variations on the benchmark, and couldn't come up with a case where the `split()` wasn't slower than `clone().split_zc()`.

With that in mind, I think there is no reason to keep a `fun split` because `fun val split` is more optimal, even when you have to `clone` first to get a `val`.

**Comment by SeanTAllen** [comment]
Closing as stale.

**Pull request closed without merging**
