### PR TITLE
Make Map.upsert return the value for the given key

### PR DESCRIPTION
**Pull request by SeanTAllen**
A change to the API for Map.upsert

### CODE REVIEW

**Comment by sylvanc** [comment]
I like this, particularly if we adopt a new syntax for chaining.

**Comment by jemc** [comment]
On a conceptual/consistency level, does the conflict with the current Pony idiom of returning the _old value_ when you do a replacement?

**Comment by SeanTAllen** [comment]
@jemc yes but upsert is also a bit of a different case. in those other cases, you know what the new value is. in the upsert case, you don't. we could return a tuple of "old value, new value". So far in using this, I've only needed new value.

**Comment by jemc** [comment]
Okay, sounds fine - I definitely have no problem with getting rid of the "return this for method chaining" when there is a useful value we can return instead.  As @sylvanc mentioned, we'll hopefully be adopting another syntax for chaining anyway.

This can probably go ahead and enter final comment period, right?

**Comment by jemc** [comment]
Yeah, I suppose if you knew you needed the old value, there would be no reason to use the `upsert` method - you could just as easily get the current value and set the new one from it, and you already have access to the old value.

**Comment by SeanTAllen** [comment]
@jemc so just a single return value or the tuple of old and new? its quite possible you wouldn't now either. so, i like the tuple idea.

**Comment by jemc** [comment]
I wasn't necessarily arguing for the tuple idea.  What would you return for the old value if there was no value for that key prior to the `upsert`?

**Comment by SeanTAllen** [comment]
Ugh. Good point. I'm inclined to leave as new value and it could be open to change later as it sees more usage.

**Comment by jemc** [comment]
Sounds good.

**Comment by SeanTAllen** [comment]
Alrighty. Welp, let's see if anyone else has comment over the next few days. I'll give this til the 31st when it can go up for a vote.

**Comment by sylvanc** [comment]
👍

**Comment by chalcolith** [comment]
:+1:

**Comment by Theodus** [comment]
:+1:

**Pull request merged**
