### PR TITLE
Use named methods instead of "apply" and "update"

### PR DESCRIPTION
**Pull request by malthe**
This is a proposal to use named methods when possible, leaving the use of the "apply" syntax sugar to function-like objects and dropping the "update" sugar altogether. This directly affects a number of classes in the standard library which currently use "apply" and "update" for methods such as getting or setting an item.

[Rendered](https://github.com/malthe/pony-rfcs/blob/8f68d898cb9d81cb8e2203765de4ac57a23aa0d2/text/0000-use-named-methods.md)

### CODE REVIEW

**Comment by jemc** [comment]
So far, I'm not convinced that this would add more value than it removes.

I quite like the current use of both `apply` and `update` in the standard library and in my own code.  I see them as being quite similar to the operator method sugar (for example, `+` calls the `add` method), and as with those, I don't think they're terribly confusing, once you're familiar with the process.  If new learners are having trouble with this in practice, maybe we can make improvements to the documentation or the tutorial to make it clearer.

If there are classes where `apply` makes for a confusing name for a method when used explicitly, I wouldn't necessarily be opposed to adding "alias methods" with more descriptive names that just call `apply` (or vice-versa).

Regarding using square brackets instead for `update` and `apply` sugar, I don't think that's a viable option.  This would be ambiguous with type parameter syntax, especially once we have dependent types, where we can put compile-time values in type parameter brackets.

**Comment by SeanTAllen** [comment]
I'm not convinced at this point in time and am leaning quite strongly against this. I would like to hear more concrete examples of:

```
The syntax sugar that some languages have for member assignment and
the like may result in less precise object interfaces that map poorly
to the underlying algorithms. The use of named methods throughout the
codebase helps steer clear of this pitfall.
```

In particular, as it relates to Pony's use of update/apply sugar that you are proposing replacing.

**Comment by malthe** [comment]
The problem that I have with the "apply" and "update" sugar on collections is that it covers so little of the interface and that the sugarless interface is just as good (and arguably more powerful).

For example, the "update" interface actually returns a previous value if there was one and we often want a "setdefault" operation that takes a lambda to create a default value. The sugar suggests that we usually want to use the simple version of getting or setting an item, but really what you want is to make the most precise choice of operation – both to make the code readable and to get the best performance.

I think that `map.get(key)` is just as succint as `map(key)` and it just makes the language easier to learn and more uniform to use.

**Comment by 0joshuaolson1** [comment]
I agree with @jemc that this looks more like a naming concern for the standard library. Also, `map(key)` is analogous to array accesses, which don't use square brackets either.

**Comment by SeanTAllen** [comment]
This seems to have stalled. Before this makes it to or out of final comment period, at the least I would like to see more conversation around what needs to change in all the pony examples, the documentation, what the level of breakage on existing code etc would be.

I'd also be interested in seeing how this impacts lambda/class interoperability.

**Comment by Theodus** [comment]
Considering how much time has passed, I think that this PR should either be closed or moved to the final comment period.

**Comment by sylvanc** [comment]
I don't see how `map.get(key)` can be considered as succinct as `map(key)`.

I also don't see how `map.set(key, value)` is as succinct as `map(key) = value`.

I think this is problematic for arrays, as indexing will no longer work (a feature very much expected in programming languages). Nor do I think think eliminating the ability to have indexing-like features on user defined classes improves the language.

As @SeanTAllen points out, this also would require lambdas to have named entry points. So instead of:

``` pony
let f = lamda(): U32 => 3 end
let x = f()
```

We would instead have:

``` pony
let f = lambda get(): U32 => 3 end
let x = f.get()
```

Similarly, partial application would have to change its syntax entirely, as it produces a lambda. That lambda would now have to have a name. I can't think of any useful way to express this syntactically.

Also, as @SeanTAllen points out, this would make lambda/class interoperability require significant planning.

Effectively, this RFC proposes to remove many core functional features from Pony. That's not something I'd like to do.

**Comment by malthe** [comment]
I think `map(key)` misses the point that a map is an object that encapsulates a hash map and provides a number of useful operations. With `map(key)` it looks like a function, but it's actually an object.

And since the method name is _apply_, it reads as an operation that will possibly change the object. I think this works well for a callable object but not so much for item retrival on a map or an array.

Just to be clear, this proposal is not about removing the apply-sugar. It's about:
1. Removing the update-sugar;
2. Using named methods for objects in the standard library.

A lambda will still be an object that's callable because the method is attached via the name `apply`.

I suppose bracket syntax might be an option if classes are required to be capitalized and variables not.

**Comment by SeanTAllen** [comment]
I don't think there is support for this change based on the comments herein, that said, I'd like to take this to final comment period and then to a vote. Are you ok with that @malthe?

**Comment by malthe** [comment]
@SeanTAllen yeah I think there are enough comments in the thread to have a vote on it.

**Comment by malthe** [comment]
I think the following examples help illustrate how named methods are more readable:
1. The documentation says that promises can be fullfilled or rejected, but in the implementation, fullfilling a promise is done through _calling_ it (via the "apply" method) instead of the obvious `fullfill()` – or `satisfy()` – which would be a direct counterpart to `reject()`.
   
   screen shot 2016-09-22 at 09 28 24
2. The HTTP client allows you to schedule a request by calling it. I think a more intuitive API would simply be `client.request(...)`.
   
   screen shot 2016-09-22 at 09 29 00
3. The status primitives in `net/http` – whether one agrees or disagrees with them – use `apply()` instead of the more obvious `code()`. And `string()` produces the status reason, which is also somewhat arbitrary. This method could simply be `reason()` instead. An HTTP status is exactly that, a code and a reason. It might be that `string()` should produce instead the two together, e.g. `"200 OK"`.

The gist here is that named methods allows us to express most clearly what a method does. The "apply" sugar is not a convenience in this context, it's a source of confusion.

**Comment by SeanTAllen** [comment]
There's nothing in this RFC as it stands that assuages my concerns about the impact on ease of use for lambdas as they now exist. I think there would be a dramatic effect where I would now have to pass a lambda with not just the correct type signature but interface as well. That would likely have a massive impact. The impact on partial application is also not addressed at all.

I think there is a small win in one area with this RFC for large losses in others. As such, as it stands I'm not in favor of this RFC.

**Comment by malthe** [comment]
@SeanTAllen, it's not mentioned in the RFC proposal because it's not related.

This RFC is not about removing the "apply" sugar, it's about not using it as a sort of "default" or primary method on an object.

I can pull out the part about removing the "update" sugar. That's all things considered orthogonal to the above concern.

**Comment by SeanTAllen** [comment]
Its very much related because the existing standard allows you to use objects or object literals interchangeably for "primary" actions. This would remove that as a possibility.

**Comment by malthe** [comment]
I think I understand what you mean.

In Java 8 you can satisfy an interface with a single method by passing a lambda:

``` java
Collections.sort(names, (a, b) -> b.compareTo(a));
```

The method here is actually called `compare` but you can still make an object literal for it because there is just a single method in the interface.

**Comment by hibnico** [comment]
I confirm, Java is more flexible in that regard. This would make a nice new RFC for Pony.

**Comment by SeanTAllen** [comment]
@malthe are you ready for a vote on this?

**Comment by malthe** [comment]
@SeanTAllen, yes.

**Comment by SeanTAllen** [comment]
We voted on this at the sync and have decided not to accept this RFC. Thank you for the time and effort that you put into this. Even if we aren't accepting this, we found the exercise of going through the RFC process valuable.

**Pull request closed without merging**
