### PR TITLE
Stateful primitives

### PR DESCRIPTION
**Pull request by Praetonus**
[Rendered](https://github.com/Praetonus/rfcs/blob/stateful-primitives/text/0000-stateful-primitives.md).

### CODE REVIEW

**Comment by jemc** [comment]
> the function and the field in the following primitive are semantically equivalent (with the exception of object identity but it is irrelevant here)

I'm not so sure you can say that object identity is irrelevant.  It may not matter much in the case of immutable data structures but that is not all you are allowing with this change.  You say that viewpoint adaptation would take care of making sure that immutable data is all that we could allow to be global, but recall that `tag` (which is still `tag` when viewpoint-adapted by `val`) is all that is required to send messages to an actor.  And this is also where object identity is very much important, regarding the distinguishing between "the function" and "the field" - "the function" creates a new actor on each invocation, and "the field" acts like a global reference to a single actor

Thus I could use fields-on-a-primitive to create a global mutable actor that runs without ever being explicitly created (and given the authority to execute) by `Main`.  I think this does count as ambient authority in a real way, whether we see it as an otherwise positive thing or not.

It's also possible that the primitive-as-entrypoint-for-a-global-actor pattern would be problematic in distributed Pony.

If we decided we wanted to adopt this RFC, but somehow make it illegal for the fields to contain an `actor` (even indirectly), I think this would end up losing the attractive simplicity it currently holds of just using viewpoint adapation and letting the normal rules apply.

**Comment by jemc** [comment]
In terms of alternatives, I think there is an important one that is not on this list.

I think Luke Cheeseman's fork with dependent types and compile-time expressions may actually fulfill a lot of the motivations for this change.  Compile-time expressions can be arbitrarily complex immutable data structures, but they may not contain actors.

**Comment by Praetonus** [comment]
Actors were on my mind but I forgot to add them in the actual text... My bad. Of course, actors should be disallowed in primitives fields. Actually we can have that guarantee for free since a primitive `_init` can't send messages and therefore can't create actors.

Compile-time expressions can solve part of the problem, but not everything. Specifically, if the data contains FFI stuff (like my SRP example, which uses the GMP C library) then it won't work.

**Comment by jemc** [comment]
> Actually we can have that guarantee for free since a primitive `_init` can't send messages and therefore can't create actors.

Right, I forgot about that constraint on `_init`.  I suppose this wouldn't be inconsistent by that metric, then.

Can you add some of this info to the text of the RFC?

**Comment by jemc** [comment]
Heh, actually looks like you just did. :smile:

**Comment by SeanTAllen** [comment]
I am generally in favor of this idea. Seems useful. I think more about Luke's work should be included in "Alternatives" including your statement:

> Compile-time expressions can solve part of the problem, but not everything. Specifically, if the data contains FFI stuff (like my SRP example, which uses the GMP C library) then it won't work.

**Comment by SeanTAllen** [comment]
Given the participants on the RFC are 3 of the most active, I think it is reasonable to take this to final comment period soon. Thoughts @jemc and @Praetonus?

**Comment by Praetonus** [comment]
I'm comfortable with moving it forward.

**Comment by Praetonus** [comment]
> I think more about Luke's work should be included in "Alternatives"

I added that.

**Comment by Praetonus** [comment]
It's been more than a week since the beginning of final comment period, marking ready for vote.

**Comment by jemc** [comment]
We want to get some input from @sylvanc before voting, in case he has any reasons not to do this that we didn't think of justifications for here.

**Comment by Praetonus** [comment]
We discussed this RFC during the sync call and it doesn't seem to be the best candidate for that use case. What we'd like to do is to use the upcoming value dependent types work to allow creating constant objects, but also allow these objects to use FFI as a way to "finish" their initialisation at runtime. I'll close this RFC and open a new one once value dependent types are available.

**Pull request closed without merging**
